FROM openjdk:11

EXPOSE 8085

# Add the JAR file generated by Maven
ADD target/spring-boot-docker.jar /spring-boot-docker.jar

# Specify the entry point to run the JAR file
ENTRYPOINT ["java", "-jar", "/spring-boot-docker.jar"]
